import type {FieldSpec} from './formFields';
const choices=(values:string[])=>values.map(value=>({value,label:value.replace(/([a-z])([A-Z])/g,'$1 $2')}));
const code:FieldSpec={name:'code',label:'Code',required:true,maxLength:30};
const name:FieldSpec={name:'name',label:'Name',required:true,maxLength:120};
const currency:FieldSpec={name:'currency',label:'Currency',required:true,choices:[{value:'NGN',label:'NGN'}],default:'NGN'};
const active:FieldSpec={name:'isActive',label:'Active',type:'checkbox',default:true};
export const rateFields:FieldSpec[]=[code,name,{name:'description',label:'Description',type:'textarea',maxLength:1000},currency,{name:'baseAdjustmentType',label:'Base adjustment',required:true,choices:choices(['None','Percentage','FixedAmount']),default:'None'},{name:'baseAdjustmentValue',label:'Adjustment value',type:'number',required:true,step:'0.01',default:0},{name:'minimumNights',label:'Minimum nights',type:'number',required:true,min:1,max:90,default:1},{name:'maximumNights',label:'Maximum nights',type:'number',required:true,min:1,max:90,default:90},{name:'sellFromDate',label:'Sell from (optional)',type:'date'},{name:'sellUntilDate',label:'Sell through (optional)',type:'date'},{name:'isDefault',label:'Default plan',type:'checkbox'},active];
export const ruleFields:FieldSpec[]=[code,name,{name:'kind',label:'Rule kind',required:true,choices:choices(['Tax','Fee']),default:'Tax'},{name:'calculation',label:'Calculation',required:true,choices:choices(['Percentage','FixedPerStay','FixedPerNight']),default:'Percentage'},{name:'value',label:'Value',type:'number',required:true,min:0.01,step:'0.01'},currency,{name:'isInclusive',label:'Already included in room price',type:'checkbox'},{name:'effectiveFromDate',label:'Effective from (optional)',type:'date'},{name:'effectiveUntilDate',label:'Effective through (optional)',type:'date'},{name:'sortOrder',label:'Calculation order',type:'number',required:true,step:'1',default:0},active];
export const promotionFields:FieldSpec[]=[{...code,maxLength:40},name,{name:'discountType',label:'Discount type',required:true,choices:choices(['Percentage','FixedAmount']),default:'Percentage'},{name:'value',label:'Discount value',type:'number',required:true,min:0.01,step:'0.01'},{name:'maximumDiscountAmount',label:'Maximum discount (optional)',type:'number',min:0.01,step:'0.01'},currency,{name:'minimumNights',label:'Minimum nights',type:'number',required:true,min:1,max:90,default:1},{name:'validFromUtc',label:'Valid from (your local time)',type:'datetime-local',required:true},{name:'validUntilUtc',label:'Valid until (your local time)',type:'datetime-local',required:true},{name:'redemptionLimit',label:'Redemption limit (optional)',type:'number',min:1,step:'1'},active];
export function validatePricing(kind:string,body:Record<string,any>){
 for(const [from,to] of [['sellFromDate','sellUntilDate'],['effectiveFromDate','effectiveUntilDate'],['validFromUtc','validUntilUtc']])if(body[from]&&body[to]&&body[to]<body[from])throw new Error('The end date must follow the start date.');
 if(body.minimumNights&&body.maximumNights&&body.maximumNights<body.minimumNights)throw new Error('Maximum nights must be at least minimum nights.');
 if(kind==='daily-rates'&&[body.roomId,body.roomTypeId,body.roomCategory].filter(Boolean).length!==1)throw new Error('Choose exactly one rate target: room, room type or category.');
 if(kind==='promotions'&&body.discountType==='Percentage'&&body.value>100)throw new Error('A percentage discount cannot exceed 100.');
}
