import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {isPrivileged} from '../lib/access';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import CatalogueEditor from '../components/CatalogueEditor';
import SchemaForm,{FieldSpec} from '../components/SchemaForm';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {words} from '../lib/operations';
type Service={id:string;name:string;description:string;category:string;price:number;isActive?:boolean};
type BookingService={id:string;serviceName:string;quantity:number;unitPrice:number;totalPrice:number;notes?:string;addedAtUtc:string};
const fields:FieldSpec[]=[{name:'name',label:'Service name',required:true,maxLength:120},{name:'description',label:'Description',type:'textarea',maxLength:500},{name:'category',label:'Service category',required:true,choices:['Dining','Wellness','Transportation','Laundry','ExecutiveServices','Other'].map(value=>({value,label:words(value)}))},{name:'price',label:'Unit price (NGN)',type:'number',required:true,min:0.01,step:'0.01'},{name:'isActive',label:'Active',type:'checkbox',default:true}];
export default function AddOns(){
 const {currentUser,bookings,refreshData}=useHotel(),confirm=useConfirmation(),managed=isPrivileged(currentUser);const [services,setServices]=useState<Service[]>([]),[entries,setEntries]=useState<BookingService[]>([]),[code,setCode]=useState(''),[revision,setRevision]=useState(0),[formVersion,setFormVersion]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[uncertain,setUncertain]=useState(false);
 useEffect(()=>{let disposed=false;setLoading(true);api.get<Service[]>(managed?'/api/addons/management':'/api/addons').then(data=>{if(!disposed)setServices(data);}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision,managed]);
 useEffect(()=>{let disposed=false;setEntries([]);if(!code)return;api.get<BookingService[]>('/api/addons/bookings/'+encodeURIComponent(code)).then(data=>{if(!disposed){setEntries(data);setUncertain(false);}}).catch(e=>{if(!disposed)setError(e.message);});return()=>{disposed=true;};},[code,revision]);
 async function save(id:string|null,body:Record<string,any>){if(busy)return false;setBusy(true);setError('');setMessage('');try{if(id)await api.put('/api/addons/'+id,body);else await api.post('/api/addons',body);setRevision(v=>v+1);setMessage('Service catalogue saved. Existing booking charges retain their price.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function add(body:Record<string,any>){if(busy||!code||uncertain)return;const service=services.find(s=>s.id===body.addOnServiceId);if(!service)return;if(!await confirm({title:'Add service to '+code+'?',message:body.quantity+' × '+service.name+' = NGN '+(body.quantity*service.price).toLocaleString()+'. This posts a charge to the guest folio.',confirmLabel:'Add service',tone:'warning'}))return;setBusy(true);setError('');setMessage('');try{const entry=await api.post<BookingService>('/api/addons/bookings/'+encodeURIComponent(code),body);setEntries(old=>[...old,entry]);setMessage('Service added to the booking and folio.');setFormVersion(v=>v+1);await refreshData({silent:true});}catch(e){setUncertain(true);setError((e as Error).message+' Refresh booking services and check the list before retrying.');}finally{setBusy(false);}}
 const bookingFields:FieldSpec[]=[{name:'addOnServiceId',label:'Service to add',required:true,choices:services.filter(s=>s.isActive!==false).map(s=>({value:s.id,label:s.name+' · NGN '+s.price}))},{name:'quantity',label:'Quantity',type:'number',required:true,min:1,max:1000,default:1},{name:'notes',label:'Service notes (optional)',type:'textarea',maxLength:300}];
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Add-on services</h1><p className="text-sm text-slate-400">Maintain the service catalogue and post itemized booking charges.</p></header><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading services…</p>}{managed&&<CatalogueEditor title="Service" items={services} fields={fields} busy={busy||loading} onSave={save} describe={s=>s.name+' · NGN '+s.price+' · '+(s.isActive?'Active':'Inactive')}/>}
 <section className="glass-card space-y-4 rounded-2xl p-5"><h2 className="font-bold">Booking services</h2><Field label="Reservation"><select disabled={busy} className={inputClass} value={code} onChange={e=>{setCode(e.target.value);setError('');setMessage('');}}><option value="">Choose reservation</option>{bookings.map(b=><option key={b.id} value={b.bookingCode}>{b.bookingCode} · {b.guestFirstName} {b.guestLastName}</option>)}</select></Field>{code&&<><button className={buttonClass} disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh booking services</button><SchemaForm key={code+'-'+formVersion} fields={bookingFields} onSubmit={add} busy={busy||loading||uncertain} submitLabel="Review service charge"/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Service','Quantity','Unit price','Total','Posted','Notes'].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{entries.map(e=><tr key={e.id}>{[e.serviceName,e.quantity,'NGN '+e.unitPrice,'NGN '+e.totalPrice,new Date(e.addedAtUtc).toLocaleString(),e.notes||'—'].map((v,i)=><td key={i} className="p-2">{v}</td>)}</tr>)}</tbody></table></div></>}</section></div>;
}
