import React,{useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import CatalogueEditor from '../components/CatalogueEditor';
import SchemaForm,{FieldSpec} from '../components/SchemaForm';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {hotelDate,words} from '../lib/operations';
import {channelTransitions,validateInbound} from '../lib/channelOperations';
import type {Page} from '../lib/pagination';
type Channel={id:string;name:string;code:string;isActive:boolean};
type Event={id:string;direction:string;status:string;eventType:string;externalReservationId?:string;attemptCount:number;createdAtUtc:string};
type Mapping={id:string;externalReservationId:string;bookingCode:string;linkedAtUtc:string};
type Summary={pendingEvents:number;failedEvents:number;deadLetterEvents:number;unmappedReservationEvents:number;oldestPendingAtUtc?:string};
export default function Channels(){
 const {bookings}=useHotel(),confirm=useConfirmation();const [channels,setChannels]=useState<Channel[]>([]),[types,setTypes]=useState<{id:string;name:string;code:string}[]>([]),[id,setId]=useState(''),[events,setEvents]=useState<Page<Event>|null>(null),[mappings,setMappings]=useState<Page<Mapping>|null>(null),[summary,setSummary]=useState<Summary|null>(null),[eventPage,setEventPage]=useState(1),[mappingPage,setMappingPage]=useState(1),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');const retry=useRef<{signature:string;key:string}|null>(null),channel=channels.find(c=>c.id===id);
 useEffect(()=>{let disposed=false;setLoading(true);Promise.all([api.get<Channel[]>('/api/channels'),api.get<typeof types>('/api/inventory/management/room-types')]).then(([c,t])=>{if(!disposed){setChannels(c);setTypes(t);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision]);
 useEffect(()=>{let disposed=false;setEvents(null);setMappings(null);setSummary(null);if(!id)return;Promise.all([api.get<Page<Event>>('/api/channels/'+id+'/events?page='+eventPage),api.get<Page<Mapping>>('/api/channels/'+id+'/reservation-mappings?page='+mappingPage),api.get<Summary>('/api/channels/'+id+'/reconciliation')]).then(([e,m,s])=>{if(!disposed){setEvents(e);setMappings(m);setSummary(s);}}).catch(e=>{if(!disposed)setError(e.message);});return()=>{disposed=true;};},[id,eventPage,mappingPage,revision]);
 async function save(channelId:string|null,body:Record<string,any>){if(busy)return false;setBusy(true);setError('');setMessage('');try{if(channelId)await api.put('/api/channels/'+channelId,body);else await api.post('/api/channels',body);setRevision(v=>v+1);setMessage('Channel configuration saved.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function operation(kind:string,body:Record<string,any>,event?:Event){if(busy||!channel)return;setError('');setMessage('');try{if(kind==='inbound')body=validateInbound(body);if(kind==='inventory'&&body.toDate<body.fromDate)throw new Error('End date must follow the start date.');}catch(e){setError((e as Error).message);return;}
 if(!await confirm({title:kind==='mapping'?'Link channel reservation?':kind==='event'?'Update event status?':'Queue channel event?',message:channel.name+'. '+(kind==='mapping'?'Link '+body.externalReservationId+' to '+(bookings.find(b=>b.id===body.bookingId)?.bookingCode||'the selected reservation')+'.':kind==='event'?'Record '+body.status+' only after checking the processing outcome.':'This records an event for the channel integration; it does not confirm external delivery.'),confirmLabel:'Save channel action',tone:'warning'}))return;
 const endpoint='/api/channels/'+(kind==='event'?'events/'+event!.id:kind==='inbound'?encodeURIComponent(channel.code)+'/events/inbound':channel.id+(kind==='mapping'?'/reservation-mappings':'/inventory-events'));
 if(['inbound','inventory'].includes(kind)){const signature=JSON.stringify({endpoint,body});if(retry.current?.signature!==signature)retry.current={signature,key:crypto.randomUUID()};body={...body,idempotencyKey:retry.current.key};}
 setBusy(true);try{if(kind==='event')await api.put(endpoint,body);else await api.post(endpoint,body);retry.current=null;setRevision(v=>v+1);setMessage('Channel action saved. Reconciliation refreshed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const fields:FieldSpec[]=[{name:'code',label:'Channel code',required:true,minLength:2,maxLength:40},{name:'name',label:'Channel name',required:true,minLength:2,maxLength:120},{name:'isActive',label:'Active',type:'checkbox',default:true}];
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Channel operations</h1><p className="text-sm text-slate-400">Channel configuration, event records and reservation reconciliation. External partner delivery requires a working integration.</p></header><StatusMessage error={error} message={message}/><CatalogueEditor title="Channel" items={channels} fields={fields} busy={busy||loading} describe={c=>c.name+' ('+c.code+') · '+(c.isActive?'Active':'Inactive')} onSave={save}/><Field label="Channel to manage"><select className={inputClass} disabled={busy||loading} value={id} onChange={e=>{setId(e.target.value);setEventPage(1);setMappingPage(1);setError('');setMessage('');retry.current=null;}}><option value="">Choose channel</option>{channels.map(c=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select></Field>
 {channel&&<><button className={buttonClass} disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Refresh channel</button>{summary&&<section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Pending',summary.pendingEvents],['Failed',summary.failedEvents],['Dead letter',summary.deadLetterEvents],['Unmapped',summary.unmappedReservationEvents]].map(([label,value])=><div className="glass-card rounded-xl p-3" key={label}><p>{label}</p><strong>{value}</strong></div>)}</section>}
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Channel events</h2>{events?.items.map(event=><article key={event.id} className="space-y-3 border-b border-white/10 py-3"><p className="font-bold">{event.eventType} · {words(event.status)}</p><p className="text-xs text-slate-400">{words(event.direction)} · {event.externalReservationId||'No reservation reference'} · Attempts {event.attemptCount} · {new Date(event.createdAtUtc).toLocaleString()}</p>{channelTransitions(event.status).length>0&&<SchemaForm key={event.id+'-'+event.status} fields={[{name:'status',label:'New event status',required:true,choices:channelTransitions(event.status).map(value=>({value,label:words(value)}))},{name:'error',label:'Failure reason (required for failed / dead letter)',type:'textarea',maxLength:1000}]} busy={busy} submitLabel="Review event update" onSubmit={body=>operation('event',body,event)}/>}</article>)}<div className="flex gap-3"><button className={buttonClass} disabled={busy||eventPage===1} onClick={()=>setEventPage(v=>v-1)}>Previous events</button><span>{eventPage} / {Math.max(1,events?.totalPages||0)}</span><button className={buttonClass} disabled={busy||!events||eventPage>=events.totalPages} onClick={()=>setEventPage(v=>v+1)}>Next events</button></div></section>
 {channel.isActive&&<><section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Queue inventory update</h2><SchemaForm key={id+'inventory'} fields={[{name:'roomTypeId',label:'Room type',required:true,choices:types.map(t=>({value:t.id,label:t.name+' ('+t.code+')'}))},{name:'fromDate',label:'First date',type:'date',required:true,default:hotelDate()},{name:'toDate',label:'Last date (inclusive)',type:'date',required:true,default:hotelDate()}]} busy={busy} onSubmit={body=>operation('inventory',body)} submitLabel="Review inventory event"/></section><details className="glass-card space-y-3 rounded-2xl p-5"><summary className="cursor-pointer font-bold">Record an inbound integration event</summary><SchemaForm key={id+'inbound'} fields={[{name:'eventType',label:'Event type',required:true,maxLength:80},{name:'externalReservationId',label:'External reservation ID (optional)',maxLength:160},{name:'payloadJson',label:'Event JSON',type:'textarea',required:true,maxLength:131072,default:'{}'}]} busy={busy} onSubmit={body=>operation('inbound',body)} submitLabel="Review inbound event"/></details></>}
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Reservation mappings</h2>{mappings?.items.map(m=><p className="break-all text-sm" key={m.id}>{m.externalReservationId} → {m.bookingCode} · {new Date(m.linkedAtUtc).toLocaleString()}</p>)}<div className="flex gap-3"><button className={buttonClass} disabled={busy||mappingPage===1} onClick={()=>setMappingPage(v=>v-1)}>Previous mappings</button><span>{mappingPage} / {Math.max(1,mappings?.totalPages||0)}</span><button className={buttonClass} disabled={busy||!mappings||mappingPage>=mappings.totalPages} onClick={()=>setMappingPage(v=>v+1)}>Next mappings</button></div>{channel.isActive&&<SchemaForm key={id+'mapping'} fields={[{name:'externalReservationId',label:'External reservation ID',required:true,maxLength:160},{name:'bookingId',label:'Hotel booking',required:true,choices:bookings.map(b=>({value:b.id,label:b.bookingCode+' · '+b.guestFirstName+' '+b.guestLastName}))}]} busy={busy} onSubmit={body=>operation('mapping',body)} submitLabel="Review reservation link"/>}</section></>}</div>;
}
