import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {isAdmin} from '../lib/access';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import SchemaForm from '../components/SchemaForm';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import type {Page} from '../lib/pagination';
type Client={id:string;name:string;email:string;phone?:string};
type Issue={userId:string;name:string;email:string;currentGuestId?:string;issue:string;emailMatches:{guestId:string;name:string;email:string;phone:string}[]};
export default function ClientAccounts(){
 const {currentUser,refreshData}=useHotel(),admin=isAdmin(currentUser),confirm=useConfirmation();const [clients,setClients]=useState<Client[]>([]),[issues,setIssues]=useState<Page<Issue>|null>(null),[id,setId]=useState(''),[issueId,setIssueId]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let disposed=false;setLoading(true);Promise.all([api.get<Client[]>('/api/admin/management/clients'),admin?api.get<Page<Issue>>('/api/admin/client-guest-links/issues?pageNumber='+page+'&pageSize=20'):Promise.resolve(null)]).then(([c,i])=>{if(!disposed){setClients(c);setIssues(i);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision,page,admin]);
 const client=clients.find(c=>c.id===id),issue=issues?.items.find(i=>i.userId===issueId);
 async function save(body:Record<string,any>){if(busy||!client)return;setError('');setMessage('');if(!await confirm({title:'Update '+client.name+'?',message:'Update this client account name and phone. Its login email, linked guest record and saved stay details remain separate.',confirmLabel:'Save account profile',tone:'warning'}))return;setBusy(true);try{await api.put('/api/admin/management/clients/'+client.id,{...body,phone:body.phone||null});setRevision(v=>v+1);setMessage('Client account profile saved. Use verified reconciliation or a privacy correction request for guest record and login identity issues.');await refreshData({silent:true});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reconcile(body:Record<string,any>){if(busy||!issue)return;if(!await confirm({title:'Reconcile client and guest?',message:issue.name+' ('+issue.email+') will link to guest '+body.guestId+'. Verify the same person owns both records before granting access to the guest history.',confirmLabel:'Reconcile verified records',tone:'warning'}))return;setBusy(true);setError('');setMessage('');try{await api.post('/api/admin/client-guest-links/'+issue.userId+'/reconcile',body);setIssueId('');setRevision(v=>v+1);setMessage('Client and guest records reconciled.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Client account care</h1><p className="text-sm text-slate-400">Correct account profiles and resolve verified guest links.</p></header><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading client accounts…</p>}<section className="glass-card space-y-4 rounded-2xl p-5"><Field label="Client account"><select disabled={busy||loading} className={inputClass} value={id} onChange={e=>{setId(e.target.value);setError('');setMessage('');}}><option value="">Choose client account</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></Field>{client&&<SchemaForm key={id+'-'+revision} initial={{fullName:client.name,phone:client.phone||''}} fields={[{name:'fullName',label:'Client full name',required:true,minLength:2,maxLength:160},{name:'phone',label:'Client phone',maxLength:30},{name:'reason',label:'Correction reason',type:'textarea',required:true,minLength:10,maxLength:500}]} busy={busy||loading} onSubmit={save} submitLabel="Review profile correction"/>}</section>
 {admin&&<section className="glass-card space-y-4 rounded-2xl p-5"><h2 className="font-bold">Client–guest link issues</h2><p className="text-sm">{issues?.totalCount??'—'} issues. Email matches are suggestions requiring identity evidence.</p><Field label="Link issue"><select disabled={busy||loading} className={inputClass} value={issue?.userId||''} onChange={e=>setIssueId(e.target.value)}><option value="">Choose issue</option>{issues?.items.map(i=><option key={i.userId} value={i.userId}>{i.name} · {i.email} · {i.issue}</option>)}</select></Field><div className="flex gap-3"><button className={buttonClass} disabled={busy||loading||page===1} onClick={()=>{setIssueId('');setPage(p=>p-1);}}>Previous issues</button><span>Page {page} / {Math.max(1,issues?.totalPages||0)}</span><button className={buttonClass} disabled={busy||loading||page>=(issues?.totalPages||0)} onClick={()=>{setIssueId('');setPage(p=>p+1);}}>Next issues</button></div>{issue&&<><p className="text-sm">Current guest: {issue.currentGuestId||'Not linked'}</p>{issue.emailMatches.map(g=><p className="text-sm" key={g.guestId}>{g.guestId} · {g.name} · {g.email} · {g.phone}</p>)}<SchemaForm key={issue.userId} fields={[{name:'guestId',label:'Verified guest ID',required:true,minLength:4,maxLength:20},{name:'evidenceType',label:'Ownership evidence',required:true,choices:['VerifiedEmail','VerifiedPhone','GovernmentId','InPersonIdentityCheck'].map(value=>({value,label:value}))},{name:'reason',label:'Evidence reason / case reference',type:'textarea',required:true,minLength:10,maxLength:500}]} busy={busy||loading} onSubmit={reconcile} submitLabel="Review reconciliation"/></>}</section>}</div>;
}
