import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {useHotel} from '../store/HotelContext';
import {isPrivileged} from '../lib/access';
import {hotelDate,words} from '../lib/operations';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {useConfirmation} from '../components/ConfirmationProvider';
type Item={bookingId:string;bookingCode:string;guestName:string;checkIn:string;checkOut:string;status:string;paymentStatus:string;amountDue:number;roomTypeName:string;roomQuantity:number;reservationRoom?:{roomTypeName:string}};
type Board={businessDate:string;arrivals:Item[];departures:Item[];inHouse:Item[];outstandingBalances:Item[];unassignedRooms:Item[];housekeeping:unknown[];maintenance:unknown[]};
type Report={payments:number;refunds:number;receivables:number;guestCredits:number;scheduledArrivals:number;actualCheckIns:number;scheduledDepartures:number;actualCheckOuts:number;pendingRefundCount:number};
type Audit={id:string;businessDate:string;closedAtUtc:string;snapshot:Report};
export default function DailyOperations(){
 const {currentUser,setActiveTab,setSelectedBookingId}=useHotel(),confirm=useConfirmation();
 const [date,setDate]=useState(hotelDate),[board,setBoard]=useState<Board|null>(null),[report,setReport]=useState<Report|null>(null),[audits,setAudits]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let disposed=false;setLoading(true);setError('');setBoard(null);setReport(null);
  Promise.all([api.get<Board>('/api/operations/board?date='+date),api.get<Report>('/api/operations/reports/operational?fromDate='+date+'&toDate='+date),api.get<Audit[]>('/api/operations/night-audits')]).then(([b,r,a])=>{if(!disposed){setBoard(b);setReport(r);setAudits(a);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});
  return()=>{disposed=true;};
 },[date,revision,currentUser?.id]);
 async function close(){if(busy||!report)return;
  if(!await confirm({title:'Close night audit for '+date+'?',message:'This saves the business-day report snapshot. Review arrivals, departures, unpaid balances and pending refunds before closing.',confirmLabel:'Close night audit',tone:'warning'}))return;
  setBusy(true);setError('');try{await api.post('/api/operations/night-audits/'+date);setMessage('Night audit snapshot saved for '+date+'.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const sections: [string,keyof Pick<Board,'arrivals'|'departures'|'inHouse'|'outstandingBalances'|'unassignedRooms'>][]=[['Arrivals','arrivals'],['Departures','departures'],['In-house','inHouse'],['Outstanding balances','outstandingBalances'],['Unassigned rooms','unassignedRooms']];
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Daily operations</h1><p className="text-sm text-slate-400">Hotel business dates in Africa/Lagos.</p></header><div className="flex flex-wrap items-end gap-3"><Field label="Business date"><input type="date" required className={inputClass} value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></Field><button className={buttonClass} disabled={loading||busy} onClick={()=>setRevision(v=>v+1)}>Refresh board</button></div><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading operations…</p>}
 {report&&<section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Payments',report.payments],['Refunds',report.refunds],['Receivables',report.receivables],['Guest credits',report.guestCredits]].map(([label,value])=><div key={label} className="glass-card rounded-xl p-4"><p className="text-xs text-slate-400">{label}</p><strong>NGN {Number(value).toLocaleString()}</strong></div>)}</section>}
 {board&&<div className="grid gap-4 lg:grid-cols-2">{sections.map(([label,key])=><section key={key} className="glass-card rounded-2xl p-4"><h2 className="mb-3 font-bold">{label} ({board[key].length})</h2><div className="max-h-80 space-y-2 overflow-auto">{!board[key].length&&<p className="text-sm text-slate-400">No records for this date.</p>}{board[key].map((item,index)=><button className="block w-full rounded-lg border border-white/10 p-3 text-left" key={item.bookingId+'-'+index} onClick={()=>{setSelectedBookingId(item.bookingId);setActiveTab('bookings');}}><strong className="text-sm">{item.bookingCode} · {item.guestName}</strong><p className="text-xs text-slate-400">{item.reservationRoom?.roomTypeName||item.roomTypeName} · {words(item.status)} {item.paymentStatus&&'· '+words(item.paymentStatus)}</p>{item.amountDue>0&&<p className="text-sm text-amber-300">Due: NGN {item.amountDue.toLocaleString()}</p>}</button>)}</div></section>)}</div>}
 {report&&<section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Night audit</h2><p className="text-sm text-slate-300">Arrivals: {report.actualCheckIns} checked in / {report.scheduledArrivals} scheduled. Departures: {report.actualCheckOuts} checked out / {report.scheduledDepartures} scheduled. Pending refunds: {report.pendingRefundCount}.</p>{isPrivileged(currentUser)&&<button className={buttonClass} disabled={busy||date>=hotelDate()||audits.some(a=>a.businessDate===date)} onClick={close}>Close night audit</button>}<p className="text-xs text-slate-400">Only completed business dates can be closed. Existing snapshots are retained.</p><ul className="space-y-2">{audits.map(a=><li key={a.id} className="rounded-lg border border-white/10 p-3 text-sm">{a.businessDate} · Closed {new Date(a.closedAtUtc).toLocaleString()} · Payments NGN {a.snapshot.payments.toLocaleString()} · Refunds NGN {a.snapshot.refunds.toLocaleString()}</li>)}</ul></section>}</div>;
}
