import React,{useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {isPrivileged} from '../lib/access';
import {useHotel} from '../store/HotelContext';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {useConfirmation} from '../components/ConfirmationProvider';
import {words} from '../lib/operations';
type Entry={id:string;type:string;direction:string;amount:number;description:string;externalReference?:string;postedAtUtc:string;notes?:string;reversesEntryId?:string};
type Folio={bookingCode:string;currency:string;status:string;amountDue:number;guestCredit:number;totalDebits:number;totalCredits:number;entries:Entry[]};
export default function Folios(){
 const {currentUser,paymentBookings,refreshData}=useHotel(),confirm=useConfirmation();
 const [code,setCode]=useState(''),[folio,setFolio]=useState<Folio|null>(null),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [action,setAction]=useState('charges'),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[reference,setReference]=useState(''),[chargeType,setChargeType]=useState('AddOnCharge'),[entryId,setEntryId]=useState(''),[statementChecked,setStatementChecked]=useState(false),[confirmReservation,setConfirmReservation]=useState(true);
 const retry=useRef<{signature:string;key:string}|null>(null);
 const privileged=isPrivileged(currentUser),finance=['finance','cashier'].includes((currentUser?.department||'').toLowerCase()),canPay=privileged||finance;
 const reset=()=>{setAmount('');setDescription('');setReference('');setEntryId('');setStatementChecked(false);retry.current=null;};
 useEffect(()=>{let disposed=false;setFolio(null);setError('');if(!code){setLoading(false);return;}setLoading(true);
  api.get<Folio>('/api/folios/'+encodeURIComponent(code)).then(data=>{if(!disposed)setFolio(data);}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};
 },[code,revision,currentUser?.id]);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy||!folio)return;setError('');setMessage('');
  const value=Number(amount);
  if(action!=='void'&&action!=='close'&&(!Number.isFinite(value)||value<=0||Math.abs(value*100-Math.round(value*100))>0.00001)){setError('Enter a positive amount with at most two decimal places.');return;}
  if(action==='payments'&&(!statementChecked||reference.trim().length<6||reference.trim().toUpperCase()===code.toUpperCase()||reference.trim().toUpperCase().startsWith('MANUAL-'))){setError('Verify the actual bank statement credit and enter its bank reference.');return;}
  const body=action==='charges'?{type:chargeType,amount:value,description,sourceType:'Staff',notes:description}:action==='payments'?{amount:value,method:'BankTransfer',externalReference:reference.trim(),confirmReservation,notes:description}:action==='credits'?{amount:value,reason:description,notes:description}:{reason:description};
  const endpoint='/api/folios/'+encodeURIComponent(code)+'/'+(action==='void'?'entries/'+entryId+'/void':action);
  if(!await confirm({title:'Save '+words(action)+' for '+code+'?',message:action==='close'?'The folio can close only after its balance and required refunds are settled.':(action==='void'?'Reverse the selected ledger entry. History is retained.':'Amount: NGN '+value.toLocaleString()+'. '+description),confirmLabel:action==='close'?'Close folio':'Post to folio',tone:'warning'}))return;
  const signature=JSON.stringify({endpoint,body});if(retry.current?.signature!==signature)retry.current={signature,key:crypto.randomUUID()};
  setBusy(true);try{const result=await api.post<Folio>(endpoint,action==='close'?undefined:{...body,idempotencyKey:retry.current.key});setFolio(result);reset();setMessage('Folio updated.');await refreshData({silent:true});}catch(e){setError((e as Error).message+' If the connection failed, retry this unchanged form to avoid a duplicate entry.');}finally{setBusy(false);}
 }
 const reversed=new Set(folio?.entries.filter(e=>e.reversesEntryId).map(e=>e.reversesEntryId));
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Guest folios</h1><p className="text-sm text-slate-400">Itemized charges, bank credits and approved ledger corrections.</p></header><Field label="Reservation"><select className={inputClass} value={code} disabled={busy} onChange={e=>{setCode(e.target.value);reset();setMessage('');}}><option value="">Choose reservation</option>{paymentBookings.map(b=><option key={b.id} value={b.bookingCode}>{b.bookingCode} · {b.guestFirstName} {b.guestLastName}</option>)}</select></Field><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading folio…</p>}
 {folio&&<><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{folio.bookingCode} · {words(folio.status)}</h2><button className={buttonClass} disabled={loading||busy} onClick={()=>setRevision(v=>v+1)}>Refresh folio</button></div><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Total charges',folio.totalDebits],['Total credits',folio.totalCredits],['Amount due',folio.amountDue],['Guest credit',folio.guestCredit]].map(([label,value])=><div className="glass-card rounded-xl p-4" key={label}><p className="text-xs text-slate-400">{label}</p><strong>{folio.currency} {Number(value).toLocaleString()}</strong></div>)}</section>
 <div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full text-left text-sm"><thead><tr>{['Posted','Entry','Description','Debit / credit','Amount','Reference'].map(label=><th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{folio.entries.map(entry=><tr key={entry.id} className="border-t border-white/10"><td className="p-3">{new Date(entry.postedAtUtc).toLocaleString()}</td><td className="p-3">{words(entry.type)}{reversed.has(entry.id)?' · reversed':''}</td><td className="p-3">{entry.description}</td><td className="p-3">{words(entry.direction)}</td><td className="p-3">{folio.currency} {entry.amount.toLocaleString()}</td><td className="max-w-64 break-all p-3">{entry.externalReference||'Not recorded'}</td></tr>)}</tbody></table></div>
 {folio.status.toLowerCase()==='open'&&<form onSubmit={submit} className="glass-card max-w-2xl space-y-4 rounded-2xl p-5"><h3 className="font-bold">Post a folio action</h3><fieldset disabled={busy} className="space-y-3"><Field label="Action"><select className={inputClass} value={action} onChange={e=>{setAction(e.target.value);reset();}}><option value="charges">Add itemized charge</option>{canPay&&<option value="payments">Record verified bank credit</option>}{privileged&&<><option value="credits">Post credit adjustment</option><option value="void">Reverse ledger entry</option></>}{canPay&&<option value="close">Close settled folio</option>}</select></Field>
 {action==='charges'&&<Field label="Charge type"><select className={inputClass} value={chargeType} onChange={e=>setChargeType(e.target.value)}>{(privileged||finance?['AddOnCharge','Tax','Fee','Adjustment']:['AddOnCharge']).map(type=><option key={type} value={type}>{words(type)}</option>)}</select></Field>}
 {action==='void'?<Field label="Entry to reverse"><select required className={inputClass} value={entryId} onChange={e=>setEntryId(e.target.value)}><option value="">Choose unreversed entry</option>{folio.entries.filter(e=>!reversed.has(e.id)&&e.type.toLowerCase()!=='void').map(entry=><option key={entry.id} value={entry.id}>{words(entry.type)} · {entry.amount} · {entry.description}</option>)}</select></Field>:action!=='close'&&<Field label="Amount (NGN)"><input className={inputClass} required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field>}
 {action==='payments'&&<><Field label="Bank statement reference"><input className={inputClass} required minLength={6} maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field label="Bank statement checked"><input type="checkbox" required checked={statementChecked} onChange={e=>setStatementChecked(e.target.checked)}/> I verified this credit on the hotel bank statement and checked it has not been used.</Field><Field label="Confirm reservation once fully paid"><input type="checkbox" checked={confirmReservation} onChange={e=>setConfirmReservation(e.target.checked)}/></Field></>}
 {action!=='close'&&<Field label="Description / reason"><textarea className={inputClass} required minLength={10} maxLength={200} value={description} onChange={e=>setDescription(e.target.value)}/></Field>}<button className={buttonClass} type="submit" disabled={action==='close'&&(folio.amountDue!==0||folio.guestCredit!==0)}>{action==='close'?'Close folio':'Review and post'}</button></fieldset></form>}</>}
 </div>;
}
