import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {isPrivileged} from '../lib/access';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import SchemaForm,{FieldSpec} from '../components/SchemaForm';
import {Field,StatusMessage,inputClass} from '../components/OperationalFields';
import {loadAllPages} from '../lib/pagination';
type Guest={id:string;firstName:string;lastName:string;email:string;phone:string};
type Profile=Guest&{emailVerifiedAtUtc?:string;phoneVerifiedAtUtc?:string;preferences:Record<string,any>;notes:{id:string;body:string;isSensitive:boolean;createdAtUtc:string}[];stayHistory:{bookingId:string;bookingCode:string;checkIn:string;checkOut:string;status:string;totalAmount:number}[]};
type Duplicate={guestId:string;guestName:string;email:string;phone:string;bookingCount:number;matchReasons:string[]};
const preferences:FieldSpec[]=[{name:'preferredLanguage',label:'Preferred language',maxLength:40},{name:'beddingPreference',label:'Bedding preference',maxLength:80},{name:'dietaryNotes',label:'Dietary notes',type:'textarea',maxLength:300},{name:'accessibilityNeeds',label:'Accessibility needs',type:'textarea',maxLength:300},{name:'marketingOptIn',label:'Guest opted into marketing',type:'checkbox'},{name:'marketingConsentReference',label:'Marketing consent evidence reference (required for new opt-in)',minLength:10,maxLength:160}];
export default function GuestCrm(){
 const {currentUser,refreshData}=useHotel(),confirm=useConfirmation(),managed=isPrivileged(currentUser);const [guests,setGuests]=useState<Guest[]>([]),[id,setId]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[duplicates,setDuplicates]=useState<Duplicate[]>([]),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let disposed=false;setLoading(true);loadAllPages<Guest>(page=>api.get('/api/guests?page='+page+'&pageSize=100')).then(data=>{if(!disposed)setGuests(data);}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision]);
 useEffect(()=>{let disposed=false;setProfile(null);setDuplicates([]);if(!id)return;Promise.all([api.get<Profile>('/api/guest-crm/'+encodeURIComponent(id)),managed?api.get<Duplicate[]>('/api/guest-crm/'+encodeURIComponent(id)+'/duplicates'):Promise.resolve([])]).then(([p,d])=>{if(!disposed){setProfile(p);setDuplicates(d);}}).catch(e=>{if(!disposed)setError(e.message);});return()=>{disposed=true;};},[id,revision,managed]);
 async function mutate(kind:string,body:Record<string,any>){if(busy||!profile)return;setError('');setMessage('');
 if(kind==='preferences'&&!body.marketingConsentReference)body.marketingConsentReference=null;
 if(kind==='merge'){const duplicate=duplicates.find(d=>d.guestId===body.duplicateGuestId);if(!duplicate||!await confirm({title:'Merge guest records?',message:'Keep '+profile.firstName+' '+profile.lastName+' ('+profile.id+'); merge '+duplicate.guestName+' ('+duplicate.guestId+'). Booking links and account ownership will be checked. This cannot be undone in the dashboard.',confirmLabel:'Merge verified duplicate',tone:'warning'}))return;body.primaryGuestId=id;}
 if(kind==='verify-contact'&&!await confirm({title:'Record verified contact?',message:'Only record evidence you have checked for '+body.contactType.toLowerCase()+'. This action does not send a verification challenge.',confirmLabel:'Record evidence',tone:'warning'}))return;
 setBusy(true);try{if(kind==='preferences')await api.put('/api/guest-crm/'+encodeURIComponent(id)+'/preferences',body);else await api.post(kind==='merge'?'/api/guest-crm/merge':'/api/guest-crm/'+encodeURIComponent(id)+'/'+kind,body);setMessage('Guest record updated.');setRevision(v=>v+1);await refreshData({silent:true});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Guest CRM</h1><p className="text-sm text-slate-400">Preferences, stay history and verified identity evidence.</p></header><StatusMessage error={error} message={message}/><Field label="Guest record"><select className={inputClass} disabled={busy||loading} value={id} onChange={e=>{setId(e.target.value);setError('');setMessage('');}}><option value="">Choose guest</option>{guests.map(g=><option key={g.id} value={g.id}>{g.firstName} {g.lastName} · {g.id} · {g.email}</option>)}</select></Field>{loading&&<p role="status">Loading guests…</p>}{profile&&<>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">{profile.firstName} {profile.lastName}</h2><p className="text-sm">{profile.email} · {profile.emailVerifiedAtUtc?'Verified '+new Date(profile.emailVerifiedAtUtc).toLocaleString():'Email not verified'}</p><p className="text-sm">{profile.phone} · {profile.phoneVerifiedAtUtc?'Verified '+new Date(profile.phoneVerifiedAtUtc).toLocaleString():'Phone not verified'}</p><SchemaForm key={id+'-'+revision} fields={preferences} initial={profile.preferences} busy={busy} onSubmit={body=>mutate('preferences',body)} submitLabel="Save preferences"/></section>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Stay history</h2><p className="text-xs text-slate-400">Most recent 100 stays. Use Bookings for the full reservation list.</p>{profile.stayHistory.map(stay=><p className="text-sm" key={stay.bookingId}>{stay.bookingCode} · {stay.checkIn.slice(0,10)} to {stay.checkOut.slice(0,10)} · {stay.status} · NGN {stay.totalAmount.toLocaleString()}</p>)}</section>
 {managed&&<><section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Guest notes</h2>{profile.notes.map(note=><article className="border-b border-white/10 py-2" key={note.id}><p className="text-xs text-slate-400">{new Date(note.createdAtUtc).toLocaleString()} · {note.isSensitive?'Sensitive':'General'}</p><p className="whitespace-pre-wrap text-sm">{note.body}</p></article>)}<SchemaForm key={id+'notes'+revision} fields={[{name:'body',label:'Note',type:'textarea',required:true,minLength:4,maxLength:1000},{name:'isSensitive',label:'Sensitive note',type:'checkbox',default:true}]} busy={busy} onSubmit={body=>mutate('notes',body)} submitLabel="Add note"/></section>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Contact verification evidence</h2><SchemaForm fields={[{name:'contactType',label:'Contact type',required:true,choices:['Email','Phone'].map(value=>({value,label:value}))},{name:'evidenceReference',label:'Verification evidence reference',required:true,minLength:4,maxLength:160}]} busy={busy} onSubmit={body=>mutate('verify-contact',body)} submitLabel="Review contact evidence"/></section>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Possible duplicate guests</h2><p className="text-sm text-slate-400">Matches are candidates, not proof of identity. Confirm ownership before merging. Use a case reference without personal documents or secrets.</p>{duplicates.map(d=><p className="text-sm" key={d.guestId}>{d.guestName} · {d.guestId} · {d.email} · {d.phone} · {d.bookingCount} bookings · {d.matchReasons.join(', ')}</p>)}{!duplicates.length?<p>No duplicate candidates found.</p>:<SchemaForm key={id+'merge'+revision} fields={[{name:'duplicateGuestId',label:'Duplicate to merge into selected guest',required:true,choices:duplicates.map(d=>({value:d.guestId,label:d.guestName+' · '+d.guestId}))},{name:'evidenceType',label:'Identity evidence type',required:true,choices:['VerifiedEmail','VerifiedPhone','GovernmentIdReviewed','ManualReview'].map(value=>({value,label:value}))},{name:'reason',label:'Non-sensitive case reference (no spaces)',required:true,minLength:10,maxLength:160}]} busy={busy} onSubmit={body=>mutate('merge',body)} submitLabel="Review guest merge"/>}</section></>}
 </>}</div>;
}
