import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import SchemaForm,{FieldSpec} from '../components/SchemaForm';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {hotelDate,words} from '../lib/operations';
type RoomType={id:string;code:string;name:string;category:string;baseOccupancy:number;maxOccupancy:number;basePricePerNight:number;description:string;amenities:string[];isActive:boolean;physicalRoomCount:number};
type Closure={id:string;roomTypeId:string;roomTypeCode:string;roomId?:string;roomNumber?:string;startDate:string;endDate:string;units:number;reason:string;isActive:boolean};
const enumChoices=(values:string[])=>values.map(value=>({value,label:words(value)}));
const typeFields:FieldSpec[]=[{name:'code',label:'Room type code',required:true,maxLength:30},{name:'name',label:'Room type name',required:true,maxLength:120},{name:'category',label:'Category',required:true,choices:enumChoices(['Standard','Deluxe','Executive','PresidentialSuite'])},{name:'baseOccupancy',label:'Base occupancy',type:'number',required:true,min:1,max:50,default:1},{name:'maxOccupancy',label:'Maximum occupancy',type:'number',required:true,min:1,max:50,default:2},{name:'basePricePerNight',label:'Base price per night (NGN)',type:'number',required:true,min:0.01,step:'0.01'},{name:'description',label:'Description',type:'textarea',maxLength:2000},{name:'amenities',label:'Amenities (comma separated)',type:'list'},{name:'isActive',label:'Active',type:'checkbox',default:true}];
export default function Inventory(){
 const {rooms,refreshData}=useHotel(),confirm=useConfirmation();const [types,setTypes]=useState<RoomType[]>([]),[closures,setClosures]=useState<Closure[]>([]),[selected,setSelected]=useState<RoomType|null>(null),[revision,setRevision]=useState(0),[formVersion,setFormVersion]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [typeId,setTypeId]=useState(''),[from,setFrom]=useState(hotelDate),[to,setTo]=useState(()=>hotelDate(new Date(Date.now()+86400000))),[availability,setAvailability]=useState<any>(null);
 useEffect(()=>{let disposed=false;setLoading(true);Promise.all([api.get<RoomType[]>('/api/inventory/management/room-types'),api.get<Closure[]>('/api/inventory/closures')]).then(([t,c])=>{if(!disposed){setTypes(t);setClosures(c);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision]);
 async function saveType(body:Record<string,any>){if(busy)return;setError('');setMessage('');if(body.maxOccupancy<body.baseOccupancy){setError('Maximum occupancy must be at least base occupancy.');return;}setBusy(true);try{if(selected)await api.put('/api/inventory/room-types/'+selected.id,body);else await api.post('/api/inventory/room-types',body);setSelected(null);setFormVersion(v=>v+1);setRevision(v=>v+1);setMessage('Room type saved.');await refreshData({silent:true});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const closureFields:FieldSpec[]=[{name:'roomTypeId',label:'Room type',required:true,choices:types.map(type=>({value:type.id,label:type.name+' ('+type.code+')'}))},{name:'roomId',label:'Specific room (optional)',choices:rooms.map(room=>({value:room.id,label:room.name}))},{name:'startDate',label:'First closed date',type:'date',required:true,default:hotelDate()},{name:'endDate',label:'Release date (exclusive)',type:'date',required:true,default:hotelDate(new Date(Date.now()+86400000))},{name:'units',label:'Units closed',type:'number',required:true,min:1,max:1000,default:1},{name:'reason',label:'Closure reason',type:'textarea',required:true,minLength:4,maxLength:500}];
 async function createClosure(body:Record<string,any>){if(busy)return;setError('');setMessage('');if(body.endDate<=body.startDate){setError('Release date must be after the first closed date.');return;}if(!await confirm({title:'Close inventory?',message:'The selected units will be unavailable during these dates. Existing reservation conflicts are checked before saving.',confirmLabel:'Create closure',tone:'warning'}))return;setBusy(true);try{await api.post('/api/inventory/closures',body);setRevision(v=>v+1);setMessage('Inventory closure created.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function release(closure:Closure){if(busy||!await confirm({title:'Release inventory closure?',message:closure.roomTypeCode+' · '+closure.startDate+' to '+closure.endDate+'. The closure stays in history.',confirmLabel:'Release closure',tone:'warning'}))return;setBusy(true);setError('');try{await api.delete('/api/inventory/closures/'+closure.id);setRevision(v=>v+1);setMessage('Inventory closure released.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function check(event:React.FormEvent){event.preventDefault();setError('');setAvailability(null);if(to<=from){setError('Check-out must be after check-in.');return;}setBusy(true);try{setAvailability(await api.get('/api/inventory/management/room-types/'+typeId+'/availability?checkIn='+from+'&checkOut='+to+'&units=1'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Inventory</h1><p className="text-sm text-slate-400">Room types, daily capacity and planned closures.</p></header><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading inventory…</p>}
 <div className="grid gap-5 xl:grid-cols-2"><section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Room types</h2>{types.map(type=><button disabled={busy} className="block w-full rounded-xl border border-white/10 p-3 text-left" key={type.id} onClick={()=>setSelected(type)}><strong>{type.name} ({type.code})</strong><p className="text-xs text-slate-400">{type.isActive?'Active':'Inactive'} · {type.physicalRoomCount} rooms · Capacity {type.maxOccupancy}</p></button>)}<button className={buttonClass} disabled={busy} onClick={()=>{setSelected(null);setFormVersion(v=>v+1);}}>New room type</button></section><section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">{selected?'Edit '+selected.name:'New room type'}</h2><SchemaForm key={(selected?.id||'new')+'-'+formVersion} fields={typeFields} initial={selected||{}} onSubmit={saveType} busy={busy||loading}/></section></div>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Daily capacity</h2><form onSubmit={check} className="grid gap-3 sm:grid-cols-4"><Field label="Room type to check"><select required disabled={busy} className={inputClass} value={typeId} onChange={e=>{setTypeId(e.target.value);setAvailability(null);}}><option value="">Choose room type</option>{types.map(type=><option key={type.id} value={type.id}>{type.name} ({type.code})</option>)}</select></Field><Field label="Check-in"><input required disabled={busy} className={inputClass} type="date" value={from} onChange={e=>{setFrom(e.target.value);setAvailability(null);}}/></Field><Field label="Check-out"><input required disabled={busy} className={inputClass} type="date" value={to} onChange={e=>{setTo(e.target.value);setAvailability(null);}}/></Field><button className={buttonClass} disabled={busy}>Check inventory</button></form>{availability&&<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Night','Physical units','Closed','Reserved','Available'].map(v=><th key={v} className="p-2">{v}</th>)}</tr></thead><tbody>{availability.days.map((day:any)=><tr key={day.stayDate}>{[day.stayDate,day.physicalUnits,day.closedUnits,day.reservedUnits,day.availableUnits].map((value,index)=><td key={index} className="p-2">{value}</td>)}</tr>)}</tbody></table></div>}</section>
 <section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Create inventory closure</h2><SchemaForm fields={closureFields} onSubmit={createClosure} busy={busy||loading} submitLabel="Review closure"/></section>
 <section className="space-y-3"><h2 className="font-bold">Closure history</h2>{closures.map(closure=><div key={closure.id} className="glass-card flex flex-wrap items-center justify-between gap-3 rounded-xl p-4"><div><strong>{closure.roomTypeCode} {closure.roomNumber&&'· Room '+closure.roomNumber}</strong><p className="text-sm">{closure.startDate} to {closure.endDate} · {closure.units} units · {closure.isActive?'Active':'Released'}</p><p className="text-xs text-slate-400">{closure.reason}</p></div>{closure.isActive&&<button className={buttonClass} disabled={busy} onClick={()=>release(closure)}>Release closure</button>}</div>)}</section></div>;
}
