import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import CatalogueEditor from '../components/CatalogueEditor';
import type {FieldSpec} from '../components/SchemaForm';
import {StatusMessage} from '../components/OperationalFields';
import {rateFields,ruleFields,promotionFields,validatePricing} from '../lib/pricingForms';
type Config={ratePlans:Record<string,any>[];dailyRates:Record<string,any>[];rules:Record<string,any>[];promotions:Record<string,any>[]};
export default function Pricing(){
 const {rooms}=useHotel(),confirm=useConfirmation();const [config,setConfig]=useState<Config>({ratePlans:[],dailyRates:[],rules:[],promotions:[]}),[types,setTypes]=useState<{id:string;name:string;code:string}[]>([]),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let disposed=false;setLoading(true);Promise.all([api.get<Config>('/api/pricing/configuration'),api.get<typeof types>('/api/inventory/management/room-types')]).then(([c,t])=>{if(!disposed){setConfig(c);setTypes(t);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[revision]);
 async function save(kind:string,id:string|null,body:Record<string,any>){if(busy)return false;setError('');setMessage('');try{validatePricing(kind,body);}catch(e){setError((e as Error).message);return false;}
 if(!await confirm({title:'Save pricing configuration?',message:'This changes future quotes. Existing accepted bookings retain their recorded price. Review the values before saving.',confirmLabel:'Save pricing',tone:'warning'}))return false;
 setBusy(true);try{if(id)await api.put('/api/pricing/'+kind+'/'+id,body);else await api.post('/api/pricing/'+kind,body);setRevision(v=>v+1);setMessage('Pricing saved. Create a fresh reservation quote to verify the result.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const plans=config.ratePlans.map(plan=>({value:plan.id,label:plan.name+' ('+plan.code+')'}));
 const dailyFields:FieldSpec[]=[{name:'ratePlanId',label:'Rate plan',required:true,choices:plans},{name:'roomId',label:'Specific room (choose one target)',choices:rooms.map(r=>({value:r.id,label:r.name}))},{name:'roomTypeId',label:'Room type (choose one target)',choices:types.map(t=>({value:t.id,label:t.name+' ('+t.code+')'}))},{name:'roomCategory',label:'Category (choose one target)',choices:['Standard','Deluxe','Executive','PresidentialSuite'].map(value=>({value,label:value}))},{name:'stayDate',label:'Stay date',type:'date',required:true},{name:'amount',label:'Nightly amount (NGN)',type:'number',required:true,min:0.01,step:'0.01'}];
 const describe=(item:Record<string,any>)=>(item.name||item.code)+' · '+(item.isActive?'Active':'Inactive')+(item.value!==undefined?' · '+item.value+' '+(item.discountType||item.calculation):'')+(item.isDefault?' · Default':'');
 async function remove(item:Record<string,any>){if(busy||!await confirm({title:'Remove daily rate?',message:item.stayDate+' · NGN '+item.amount+'. Future quotes will use the next applicable rate.',confirmLabel:'Remove rate',tone:'warning'}))return;setBusy(true);setError('');try{await api.delete('/api/pricing/daily-rates/'+item.id);setRevision(v=>v+1);setMessage('Daily override removed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Pricing</h1><p className="text-sm text-slate-400">Manage future quotes. Disable old plans, rules or promotions to retain their history.</p></header><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading pricing…</p>}<div className="grid gap-5 xl:grid-cols-2"><CatalogueEditor title="Rate plan" items={config.ratePlans} fields={rateFields} busy={busy||loading} describe={describe} onSave={(id,body)=>save('rate-plans',id,body)}/><CatalogueEditor title="Daily rate" items={config.dailyRates} fields={dailyFields} busy={busy||loading} describe={item=>item.stayDate+' · '+(config.ratePlans.find(p=>p.id===item.ratePlanId)?.code||'Plan')+' · '+(rooms.find(r=>r.id===item.roomId)?.name||types.find(t=>t.id===item.roomTypeId)?.name||item.roomCategory)+' · NGN '+item.amount} onSave={(id,body)=>save('daily-rates',id,body)} onRemove={remove}/><CatalogueEditor title="Tax or fee" items={config.rules} fields={ruleFields} busy={busy||loading} describe={describe} onSave={(id,body)=>save('rules',id,body)}/><CatalogueEditor title="Promotion" items={config.promotions} fields={[...promotionFields,{name:'ratePlanId',label:'Rate plan restriction (optional)',choices:plans}]} busy={busy||loading} describe={item=>describe(item)+' · Used '+item.redemptionCount+'/'+(item.redemptionLimit??'unlimited')} onSave={(id,body)=>save('promotions',id,body)}/></div></div>;
}
