import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import SchemaForm,{FieldSpec} from '../components/SchemaForm';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import {hotelDate,words} from '../lib/operations';
type Type={id:string;name:string;code:string;maxOccupancy:number};
type Quote={quoteId:string;quoteToken:string;totalAmount:number;currency:string;expiresAtUtc:string;lines:{description:string;amount:number}[]};
type Unit={id:string;sequence:number;roomTypeId:string;roomTypeName:string;assignedRoomId?:string;assignedRoomName?:string;assignedRoomNumber?:string};
type Reservation={id:string;bookingCode:string;status:string;roomTypeId:string;roomQuantity:number;adultCount:number;childCount:number;checkIn:string;checkOut:string;amount:number;rooms:Unit[]};
type Amendment={id:string;reason:string;previousAmount:number;newAmount:number;amendedAtUtc:string};
type Policy={privacyPolicyVersion:string;bookingTermsVersion:string;privacyPolicyUrl:string;bookingTermsUrl:string;acceptanceRequired?:boolean};
export default function ReservationOperations(){
 const {bookings,rooms,refreshData}=useHotel(),confirm=useConfirmation();
 const [code,setCode]=useState(''),[types,setTypes]=useState<Type[]>([]),[policy,setPolicy]=useState<Policy|null>(null),[booking,setBooking]=useState<Reservation|null>(null),[history,setHistory]=useState<Amendment[]>([]),[quote,setQuote]=useState<Quote|null>(null),[quotedInput,setQuotedInput]=useState<Record<string,any>|null>(null),[accepted,setAccepted]=useState(false),[revision,setRevision]=useState(0),[formVersion,setFormVersion]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [unitId,setUnitId]=useState(''),[roomId,setRoomId]=useState(''),[assignmentReason,setAssignmentReason]=useState('');
 useEffect(()=>{let disposed=false;Promise.all([api.get<Type[]>('/api/inventory/room-types'),api.get<Policy>('/api/privacy/policies/current')]).then(([t,p])=>{if(!disposed){setTypes(t);setPolicy(p);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[]);
 useEffect(()=>{let disposed=false;setBooking(null);setHistory([]);setQuote(null);setQuotedInput(null);setAccepted(false);setUnitId('');setRoomId('');setAssignmentReason('');if(!code){setLoading(false);return;}setLoading(true);
  api.get<Reservation>('/api/bookings/'+encodeURIComponent(code)).then(async b=>{const h=await api.get<Amendment[]>('/api/reservations/'+b.id+'/amendments');if(!disposed){setBooking(b);setHistory(h);}}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};
 },[code,revision]);
 const fields:FieldSpec[]=[...(!code?[{name:'guestFirstName',label:'Guest first name',required:true,maxLength:80},{name:'guestLastName',label:'Guest last name',required:true,maxLength:80},{name:'guestEmail',label:'Guest email',type:'email' as const,required:true,maxLength:254},{name:'guestPhone',label:'Guest phone',required:true,minLength:7,maxLength:30}]:[]),
 {name:'roomTypeId',label:'Room type',required:true,choices:types.map(t=>({value:t.id,label:t.name+' ('+t.code+') · capacity '+t.maxOccupancy+' per room'}))},{name:'roomQuantity',label:'Number of rooms',type:'number',required:true,min:1,max:10,default:1},{name:'checkIn',label:'Check-in',type:'date',required:true,default:hotelDate(new Date(Date.now()+86400000))},{name:'checkOut',label:'Check-out',type:'date',required:true,default:hotelDate(new Date(Date.now()+2*86400000))},{name:'adultCount',label:'Adults',type:'number',required:true,min:1,max:20,default:1},{name:'childCount',label:'Children',type:'number',required:true,min:0,max:20,default:0},{name:'ratePlanCode',label:'Rate plan code (optional)',maxLength:30},{name:'promotionCode',label:'Promotion code (optional)',maxLength:40},...(code?[{name:'reason',label:'Amendment reason',type:'textarea' as const,required:true,minLength:10,maxLength:500}]:[{name:'notes',label:'Booking notes (optional)',type:'textarea' as const,maxLength:1000}])];
 const initial=booking?{...booking,checkIn:booking.checkIn.slice(0,10),checkOut:booking.checkOut.slice(0,10)}:{};
 const datePayload=(body:Record<string,any>)=>({...body,checkIn:body.checkIn+'T00:00:00',checkOut:body.checkOut+'T00:00:00',roomId:null,ratePlanCode:body.ratePlanCode||null,promotionCode:body.promotionCode||null});
 async function price(body:Record<string,any>){if(busy)return;setError('');setMessage('');setQuote(null);if(body.checkOut<=body.checkIn){setError('Check-out must be after check-in.');return;}setBusy(true);try{const payload=datePayload(body);const result=await api.post<Quote>(booking?'/api/reservations/'+booking.id+'/amendment-quotes':'/api/pricing/quotes',payload);setQuote(result);setQuotedInput(payload);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(busy||!quote||!quotedInput||!policy)return;if(!booking&&policy.acceptanceRequired&&!accepted){setError('Record guest acceptance of the current privacy notice and booking terms.');return;}
  if(!await confirm({title:booking?'Apply reservation amendment?':'Create pending group reservation?',message:quote.currency+' '+quote.totalAmount.toLocaleString()+'. '+(booking?'The existing booking and folio will reflect the new dates, room count and price.':'Bank transfer remains pending until hotel staff verify the credit.'),confirmLabel:booking?'Apply amendment':'Create reservation',tone:'warning'}))return;
  setBusy(true);setError('');try{const body={...quotedInput,quoteId:quote.quoteId,quoteToken:quote.quoteToken};
   if(booking)await api.post('/api/reservations/'+booking.id+'/amendments',body);
   else{const result=await api.post<{bookingCode:string;booking?:{bookingCode:string}}>('/api/bookings',{...body,paymentMethod:'DirectTransfer',acceptPrivacyPolicy:accepted,acceptBookingTerms:accepted,privacyPolicyVersion:policy.privacyPolicyVersion,bookingTermsVersion:policy.bookingTermsVersion});setMessage('Pending reservation created: '+(result.bookingCode||result.booking?.bookingCode||'refresh bookings to view')+'. Awaiting verified bank payment.');setFormVersion(v=>v+1);}
   if(booking)setMessage('Reservation amended.');setQuote(null);setQuotedInput(null);setAccepted(false);setRevision(v=>v+1);await refreshData({silent:true});
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function assign(event:React.FormEvent){event.preventDefault();if(busy||!booking)return;if(!await confirm({title:'Assign selected room?',message:'The hotel will check dates, capacity and physical room readiness before changing the assignment.',confirmLabel:'Assign room',tone:'warning'}))return;setBusy(true);setError('');try{await api.put('/api/inventory/bookings/'+booking.id+'/rooms/'+unitId+'/assignment',{roomId,reason:assignmentReason});setMessage('Room assignment updated.');setRevision(v=>v+1);await refreshData({silent:true});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const editable=!booking||['pending','confirmed'].includes(booking.status.toLowerCase());
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Reservation operations</h1><p className="text-sm text-slate-400">Group reservations, quoted amendments and physical room assignments.</p></header><Field label="Reservation to manage"><select className={inputClass} disabled={busy} value={code} onChange={e=>{setCode(e.target.value);setError('');setMessage('');}}><option value="">Create a group reservation</option>{bookings.map(b=><option key={b.id} value={b.bookingCode}>{b.bookingCode} · {b.guestFirstName} {b.guestLastName}</option>)}</select></Field><StatusMessage error={error} message={message}/>{loading&&<p role="status">Loading reservation operations…</p>}
 {!loading&&(!code||booking)&&<><section className="glass-card space-y-4 rounded-2xl p-5"><h2 className="font-bold">{booking?booking.bookingCode+' · '+words(booking.status):'New group reservation'}</h2>{editable?<SchemaForm key={code+'-'+revision+'-'+formVersion} fields={fields} initial={initial} onSubmit={price} onChange={()=>{setQuote(null);setQuotedInput(null);}} busy={busy||!policy} submitLabel="Get current quote"/>:<p className="text-sm text-slate-400">This reservation state cannot be amended.</p>}
 {quote&&<section className="space-y-3 rounded-xl border border-brand-500/40 p-4"><h3 className="font-bold">Current quote: {quote.currency} {quote.totalAmount.toLocaleString()}</h3><ul className="space-y-1 text-sm">{quote.lines.map((line,index)=><li key={index}>{line.description} · {quote.currency} {line.amount.toLocaleString()}</li>)}</ul><p className="text-xs text-slate-400">Quote expires {new Date(quote.expiresAtUtc).toLocaleString()}. Changes to the form require a new quote.</p>{!booking&&policy&&<label className="block text-sm"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> The guest accepts the <a className="underline" href={policy.privacyPolicyUrl} target="_blank" rel="noreferrer">Privacy Notice</a> and <a className="underline" href={policy.bookingTermsUrl} target="_blank" rel="noreferrer">Booking Terms</a>.</label>}<button className={buttonClass} disabled={busy||(!booking&&Boolean(policy?.acceptanceRequired)&&!accepted)||Date.parse(quote.expiresAtUtc)<=Date.now()} onClick={save}>{booking?'Review amendment':'Review reservation'}</button></section>}</section>
 {booking&&<section className="glass-card space-y-3 rounded-2xl p-5"><h2 className="font-bold">Assigned rooms</h2>{booking.rooms.map(unit=><p key={unit.id} className="text-sm">Unit {unit.sequence} · {unit.roomTypeName} · {unit.assignedRoomName||unit.assignedRoomNumber||'Assignment pending'}</p>)}{['pending','confirmed'].includes(booking.status.toLowerCase())&&<form onSubmit={assign} className="grid gap-3 sm:grid-cols-2"><Field label="Reservation unit"><select className={inputClass} required value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Choose unit</option>{booking.rooms.map(unit=><option key={unit.id} value={unit.id}>Unit {unit.sequence} · {unit.roomTypeName}</option>)}</select></Field><Field label="Physical room"><select className={inputClass} required value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Choose room</option>{rooms.map(room=><option key={room.id} value={room.id}>{room.name} · {words(room.status)}</option>)}</select></Field><Field label="Assignment reason"><input className={inputClass} required minLength={4} maxLength={500} value={assignmentReason} onChange={e=>setAssignmentReason(e.target.value)}/></Field><button disabled={busy} className={buttonClass}>Review assignment</button></form>}</section>}
 {booking&&<section className="space-y-3"><h2 className="font-bold">Amendment history</h2>{history.map(item=><div key={item.id} className="glass-card rounded-xl p-4"><p>{new Date(item.amendedAtUtc).toLocaleString()} · NGN {item.previousAmount.toLocaleString()} → {item.newAmount.toLocaleString()}</p><p className="text-sm text-slate-400">{item.reason}</p></div>)}{!history.length&&<p className="text-sm text-slate-400">No amendments recorded.</p>}</section>}</>}</div>;
}
