import React,{useEffect,useState} from 'react';
import {api} from '../lib/api';
import {isAdmin} from '../lib/access';
import {useHotel} from '../store/HotelContext';
import {useConfirmation} from '../components/ConfirmationProvider';
import {Field,StatusMessage,inputClass,buttonClass} from '../components/OperationalFields';
import type {Page} from '../lib/pagination';
type Job={id:string;reference:string;sourceType:string;attemptCount:number;lastErrorCode?:string;createdAtUtc:string;canRetry:boolean};
export default function RetryJobs(){
 const {currentUser}=useHotel(),admin=isAdmin(currentUser),confirm=useConfirmation();const [kind,setKind]=useState('media'),[page,setPage]=useState(1),[data,setData]=useState<Page<Job>|null>(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const base=kind==='email'?'/api/operations/email-outbox':'/api/admin/media-deletions';
 useEffect(()=>{let disposed=false;setLoading(true);setData(null);api.get<Page<Job>>(base+(kind==='email'?'/dead-letters/page':'/failed/page')+'?page='+page+'&pageSize=20').then(result=>{if(!disposed)setData(result);}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[base,kind,page,revision]);
 async function retry(job:Job){if(busy||!job.canRetry||!await confirm({title:kind==='email'?'Retry this email?':'Retry this media deletion?',message:job.reference+'. '+(kind==='email'?'The previously queued business email will be eligible for delivery again.':'The worker will retry deletion of the referenced media and check its current use.'),confirmLabel:'Queue retry',tone:'warning'}))return;setBusy(true);setError('');setMessage('');try{await api.post(base+'/'+job.id+'/retry');setMessage('Retry queued. This does not confirm completion; the worker processes it asynchronously.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold">Failed delivery jobs</h1><p className="text-sm text-slate-400">Review jobs that have exhausted automatic retries. Correct the provider issue before retrying.</p></header><StatusMessage error={error} message={message}/><Field label="Job queue"><select className={inputClass} disabled={busy} value={kind} onChange={e=>{setKind(e.target.value);setPage(1);setError('');setMessage('');}}><option value="media">Media deletion</option>{admin&&<option value="email">Email delivery</option>}</select></Field><button className={buttonClass} disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Refresh failed jobs</button>{loading?<p role="status">Loading failed jobs…</p>:<><p>{data?.totalCount??'—'} failed jobs</p>{data?.items.map(job=><article className="glass-card space-y-2 rounded-xl p-4" key={job.id}><h2 className="break-all font-bold">{job.reference}</h2><p className="text-sm">{job.sourceType} · Attempts {job.attemptCount} · {job.lastErrorCode||'No error code recorded'}</p><p className="text-xs text-slate-400">{new Date(job.createdAtUtc).toLocaleString()} · {job.id}</p>{job.canRetry?<button className={buttonClass} disabled={busy} onClick={()=>retry(job)}>Review retry</button>:<p className="text-sm text-amber-300">Privacy-scrubbed message cannot be replayed. Review the originating business action if a replacement is required.</p>}</article>)}<div className="flex gap-3"><button className={buttonClass} disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Previous jobs</button><span>Page {page} / {Math.max(1,data?.totalPages||0)}</span><button className={buttonClass} disabled={busy||page>=(data?.totalPages||0)} onClick={()=>setPage(p=>p+1)}>Next jobs</button></div></>}</div>;
}
